# Generated by Django 5.0 on 2024-03-01 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='books_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
